site_name: FIAE Wiki

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: color_mode

nav:
  - Wirtschaft:
    - wirtschaft/index.md
    - Wertsch√∂pfungskette: wirtschaft/wertschoepfungskette.md
    - Qualitativer Angebotsvergleich / Nutzwertanalyse: wirtschaft/nutzwertanalyse.md
    - Quantitativer Angebotsvergleich / Handelskalkulation: wirtschaft/handelskalkulation.md
    - Markt: wirtschaft/markt.md
    - Marketing: wirtschaft/marketing.md
    - Finanzierung: wirtschaft/finanzierung.md
    - Entgeltabrechnung & Sozialabgaben: wirtschaft/entgeltabrechnung.md
    - Wirtschaftlichkeitsbetrachtung & wirtschaftliche Kennzahlen: wirtschaft/wirtschaftlichkeit.md
  - Recht:
    - recht/index.md
  - IT-Sicherheit:
    - it-sicherheit/index.md
  - Projektmanagement:
    - projektmanagement/index.md
  - Netzwerke:
    - netzwerke/index.md
  - Software:
    - software/index.md
  - about.md